apiVersion: batch/v1
kind: Job
metadata:
  name: batch-extract
spec:
  completions: 1   # Only 1 pod is required to complete the job
  parallelism: 1   # Only 1 pod runs at a time
  template:
    metadata:
      name: batch-extract-pod
    spec:
      containers:
      - name: batch-extract-container
        image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python
        command: ["/bin/bash", "-c"]
        args:
          - |
            #!/bin/bash
            cd /mnt/synrs3d/SynRS3D/data;
            bash extract_files.sh;
        resources:
          limits:
            memory: "32Gi"
            cpu: "4"
          requests:
            memory: "8Gi"
            cpu: "2"
        volumeMounts:
        - mountPath: /mnt/synrs3d
          name: pvc-storage
        securityContext:
          runAsUser: 0
      volumes:
      - name: pvc-storage
        persistentVolumeClaim:
          claimName: synrs3d-test
      restartPolicy: Never
  backoffLimit: 1
