apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 1Gi
        cpu: 1
      requests:
        nvidia.com/gpu: 1
        memory: 1Gi
        cpu: 1
    volumeMounts:
    - name: data
      mountPath: /data
    securityContext:
      runAsUser: 0
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: synrs3d-test