apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 62d4e4e7c262b18c7f65a14c97a297d045861420224291fc075d8a385d9ad50a
    cni.projectcalico.org/podIP: 10.244.56.178/32
    cni.projectcalico.org/podIPs: 10.244.56.178/32
  creationTimestamp: "2025-01-14T18:03:36Z"
  name: pvc-test-pod
  namespace: gp-engine-malof
  resourceVersion: "9343625283"
  uid: a4f79ca5-efbc-47c9-87e1-a12e5fa311f4
spec:
  activeDeadlineSeconds: 21600
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep infinity
    image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python
    imagePullPolicy: Always
    name: pvc-test-container
    resources:
      limits:
        cpu: "4"
        memory: 16Gi
        nvidia.com/gpu: "1"
      requests:
        cpu: "4"
        memory: 16Gi
        nvidia.com/gpu: "1"
    securityContext:
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/data
      name: pvc-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hb7jj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-haosu-21.sdsc.optiputer.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: PreferNoSchedule
    key: nvidia.com/gpu
    operator: Exists
  - effect: NoSchedule
    key: nautilus.io/gp-engine-malof
    operator: Exists
  volumes:
  - name: pvc-storage
    persistentVolumeClaim:
      claimName: synrs3d-test
  - name: kube-api-access-hb7jj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-01-14T18:03:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-01-14T18:03:42Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-01-14T18:03:42Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-01-14T18:03:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://d2473256244699a293e9e471bd38ae3f03c8e7d699dfacc6331f39caf88cbb7e
    image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:latest
    imageID: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python@sha256:2804d8ddc158f40197d23310c186dbbb963b39bc95826a7b82489681297dca41
    lastState: {}
    name: pvc-test-container
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-01-14T18:03:42Z"
  hostIP: 67.58.51.246
  phase: Running
  podIP: 10.244.56.178
  podIPs:
  - ip: 10.244.56.178
  qosClass: Guaranteed
  startTime: "2025-01-14T18:03:36Z"
