apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synrs3d-test
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi