apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
spec:
  containers:
  - name: pvc-test-container
    image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python
    command: ["/bin/sh", "-c", "sleep infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: "16Gi"
        cpu: "4"
      requests:
        nvidia.com/gpu: 1
        memory: "16Gi"
        cpu: "4"
    volumeMounts:
    - mountPath: /mnt/data
      name: pvc-storage
    securityContext:
      runAsUser: 0
  volumes:
  - name: pvc-storage
    persistentVolumeClaim:
      claimName: synrs3d-test